#!/usr/bin/env python3
import sys
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# لو الملف اتشغل من /usr/bin
if not os.path.exists(os.path.join(BASE_DIR, "main.py")):
    BASE_DIR = os.path.expanduser("~/Vortex-ip")

sys.path.insert(0, BASE_DIR)

from main import main

if __name__ == "__main__":
    main()